#!/bin/bash

src=$1
dest=$2
mntpoint=.tmp

fixperms() {
	shopt -s dotglob nullglob
	for obj in $1/*; do
		if [[ -d "$obj" ]]; then
			chmod 755 "$obj"
			fixperms "$obj"
		elif [[ -x "$obj" ]]; then
			chmod 755 "$obj"
		else
			chmod 644 "$obj"
		fi
	done
}

mkdir -p $mntpoint "$dest"
sudo mount -t affs -o loop --source "$src" --target $mntpoint

if [[ -n `ls -A "$mntpoint"` ]]; then
	shopt -s dotglob nullglob
	sudo cp -R $mntpoint/* "$dest"
fi

sudo umount $mntpoint
rm -r $mntpoint

if [[ -d "$dest" ]]; then
	sudo chown -R $USER:$USER "$dest"
	fixperms "$dest"
fi